os: windows # windows | linux | osx
level: 1 # Difficulty level 1-5
status: draft # could be active | disabled | draft
question: question.md
editorfiles:
    - file1: file1.py
    - file2: file2.py
    - file3: file3.py
setup:
    term: termstart.txt
    editor:
        openfiles:
            - helloworld.py: file1
            - test.py: file2
answer:
    term: termcmd.txt
    editor:
        openfiles:
            - helloworld.py: file1
            - test.py: file2
effects:
    term: termoutput.txt
    editor:
        openfiles:
            - helloworld.py: file1
            - test.py: file3
comments: >
    file1 and file2 stay unchanged from question to
    answer stage, but in the output stage, one of the
    files changes. The files section structure is of
    the form - "filename": localfileforvalues

    This .yaml is an intermediate that allows me to
    store the question metadata in files. When uploading
    to the server, I will make json structures, where
    the actual file contents will get written into the
    required fields as base64 (or 32 or whatever)
    encoding, and then decode upstream. Compression can
    also get involved as some point.

    The files appear in their own section, because we
    only need that to tell us which files will be
    involved.  Once we know that we can do the
    substitution operations when necessary
    according to the recipe.
