os: windows # windows | linux | osx
level: 1 # Difficulty level 1-5
status: draft # could be active | disabled | draft
setup:
    script: mkfs.py
sequence: # Must be ordered (sequence!)
    - question_format: md
      question: >
        # Delete a file

        First list the contents.
      filesystem: fs1.yaml
      answer:
            term_format: txt
            term: 'dir'
            termoutput: t1.txt
    - question_format: md
      question: >
        # Delete a file

        Get rid of the file `secrets.txt`.
      filesystem: fs2.yaml
      answer:
            term_format: txt
            term: 'del secrets.txt'
            termoutput: t2.txt
    - question_format: md
      question: >
        # Rename with `move`

        List the contents. The file is gone.
      filesystem: fs3.yaml
      answer:
            term_format: txt
            term: 'dir'
            termoutput: t3.txt
